### ISSUE TITLE
Does the 1024x576 model work for portrait images?

### ISSUE THREAD

**Issue by doogyhatts** [thu-ml/cond-image-leakage#2]
Just wondering about the usage of the model for the 576x1024 portrait resolution.
Or is the 1024x576 model specifically catered to only the landscape format?

**Comment by zhuhz22** [comment]
Yes. We finetuned the original DynamiCrafter model on Webvid-2M,which contains portraits,so the model is expected to work for portrait images.You could have a try on `examples/DynamiCrafter/inference_CIL_1024.sh` .Here are some [demos](https://github.com/thu-ml/cond-image-leakage/blob/main/assets/1024demos).

**Comment by doogyhatts** [comment]
Thanks for the reply. I will feedback to Kijai.
