### ISSUE TITLE
1024 model still has watermark

### ISSUE THREAD

**Issue by doogyhatts** [thu-ml/cond-image-leakage#5]
Unfortunately, the re-uploaded 10gb model still has watermark. So it is not watermark-free.
Just wondering if you will be providing a totally no-watermark model for the 576x1024 resolution?

**Comment by zhuhz22** [comment]
Hi @edwinzeng2005 ,
I didn't find watermarks on my imagebenchmark,and the demo in `prompts/1024` didn't produce watermarks either.Maybe you could show an example with watermark? I'll fix the problem if so.

**Comment by doogyhatts** [comment]
I think I have made a mistake in my test run, so I will redo it again with the 10gb model.

**Comment by doogyhatts** [comment]
Ok it is watermark-free for the first result from the 10gb model.
Very nice!

I will check again with the pruned model later.
