### ISSUE TITLE
About compromising other performance

### ISSUE THREAD

**Issue by CIntellifusion** [thu-ml/cond-image-leakage#6]
Thanks for your excellent work. From the demo videos, we can see the other aspects like image quality is not affected. But I still wondering whether there would be quantitative experiments to further validate how the performance on the other aspects changes? 
thanks for your reply.

**Comment by zhuhz22** [comment]
Hi @CIntellifusion ,
Thank you for your attention to our work! Actually, there is a certain trade-off between dynamics, temporal consistency, and the quality of generation. **In our inference strategy, if the initial M is set appropriately, it is possible to enhance motion without compromising *image alignment* and *temporal consistency***.
As for the  ***quantitative comparison***, in our paper, we validated these aspects in the user study where M is properly set: 
![image](https://github.com/user-attachments/assets/18cf3fe3-65dd-4dd2-959b-05cae7fe4dda)
However, if M is set too low, it will impact temporal consistency and the quality of generation. You can try experimenting with the code yourself to get a feel for it.

**Comment by CIntellifusion** [comment]
Hi! It is really hard to achieve better performance in one dimension while maintain the same performance in other dimension, but the user study has basically proved the gained performance is larger than lost performance. Thanks for providing a new perspective of image leakage! REALLY NICE WORK.
